### ISSUE TITLE
WTFCavebiomes Flint item ID has meta (318:5)

### ISSUE THREAD

**Issue by Dulciphi** [WhiskyTangoFawks/WTFCavebiomes#2]
..this is a small annoyance, as it means flint dropped from breaking WTF sedimentary sands doesn't stack with flint dropped from/craft from gravel. Additionally, it cannot be used to craft vanilla arrows, or indeed most other flint recipes.

Again, it's a small annoyance. I can easily adjust the arrow recipe to ignore meta, and/or make a recipe  to exchange WTF flint for vanilla flint but there might be other users who can't. 

..it's just occurred to me that the flint ID meta might be intentional, and there's another use for WTF flint that I'm overlooking. Apologies if that's the case, but I'm curious to know what it is.

It's great that flint drops from the sedimentary sands like that, by the way. I'd love to add dusts, shards and nuggets to their drops list (with very low drop rates, of course) but I've still not learned how to make a PR.

**Comment by WhiskyTangoFawks** [comment]
I wasn't aware of it doing that- it was a side effect of me extending the class from gravel to get UBCSand to fall.  I've addressed the issue.  It should now be calling the rare drops from UBC's Sedimentary Stone instead.  Fix will ship with the next build.
