### ISSUE TITLE
Mummy Armour Crash

### ISSUE THREAD

**Issue by Wobbert** [WhiskyTangoFawks/WTFCavebiomes#4]
I made a custom spawner with that would spawn zombies wearing the mummy armor using the setblock command, and now my game crashes when I load up the world I did this in. Also, sorry if this report is shit in anyway, this is my first time having to actually file a crash report.

Version of cave biomes: 1.53

Version of Forge: 10.13.4.1566

Command: /setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {EntityId:Zombie,SpawnData:{Equipment:[{},{id:mummy_boots},{id:mummy_leggings},{id:mummy_chestplate},{id:mummy_helmet}]}}. 

Crash report: http://pastebin.com/BQerpphy

(Edit) After testing the command with only Cave Biomes, the spawner did not cause any crashes, the same is true when done with vanilla armour. It's also worth noting that in both tests the command just placed a normal zombie spawner. Anyway, thanks for the help.

**Comment by WhiskyTangoFawks** [comment]
Not entirely sure what caused this.  The first part of troubleshooting it is to confirm that no other mods are contributing to it, so try it again with nothing but cavebiomes and it's dependencies installed.  Secondly, confirm that your command is working correctly by spawning a zombie with a vanilla set of armour.  With any luck, one of those things will tell us what's going on.
